============================================================
           AI USAGE DECLARATION
============================================================

Name: Khandaker Ziaur Rahman
Student ID: 24141125
Assignment: Assignment 2 
Date: 22 February 2026

------------------------------------------------------------
1. AI TOOLS USED (check all that apply)
------------------------------------------------------------
[ ] None
[x] ChatGPT
[ ] GitHub Copilot
[ ] Google Gemini
[ ] Claude
[ ] Cursor
[ ] Other: ________________

------------------------------------------------------------
2. PURPOSE OF AI USE (check all that apply)
------------------------------------------------------------
[ ] Learning/understanding concepts
[ ] Debugging my code
[ ] Generating code snippets
[x] Writing text content
[ ] Design/styling ideas
[ ] Image generation
[ ] Other: ________________

------------------------------------------------------------
3. DESCRIPTION OF AI USE
------------------------------------------------------------
AI was used only to assist in writing and formatting the
README.md documentation file. The AI helped improve wording,
structure, and presentation of project documentation.
No project logic or implementation code was generated by AI.

------------------------------------------------------------
4. AI-ASSISTED SECTIONS
------------------------------------------------------------
File: README.md        Section: Project documentation and formatting

------------------------------------------------------------
5. DECLARATION
------------------------------------------------------------
I declare that:
- This disclosure is complete and accurate
- I understand all code in my submission
- I can explain and modify my work if asked
- I take full responsibility for my submission

Signature: Khandaker Ziaur Rahman
Date: 22 February 2026